

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "InputSettingsPane.xaml.h"




void ::Win8Snes9x::InputSettingsPane::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///InputSettingsPane.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///InputSettingsPane.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the ToggleSwitch named 'assignControlToggle'
    assignControlToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"assignControlToggle"));
    // Get the ToggleSwitch named 'touchToggle'
    touchToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"touchToggle"));
    // Get the ToggleSwitch named 'buttonStyleToggle'
    buttonStyleToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"buttonStyleToggle"));
    // Get the ToggleSwitch named 'touchControlPosToggle'
    touchControlPosToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"touchControlPosToggle"));
    // Get the ToggleSwitch named 'touchButtonStyleToggle'
    touchButtonStyleToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"touchButtonStyleToggle"));
    // Get the TextBlock named 'dpadStyleLabel'
    dpadStyleLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"dpadStyleLabel"));
    // Get the ComboBox named 'dpadComboBox'
    dpadComboBox = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"dpadComboBox"));
    // Get the Slider named 'deadzoneSlider'
    deadzoneSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"deadzoneSlider"));
    // Get the Slider named 'controllerScaleSlider'
    controllerScaleSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"controllerScaleSlider"));
    // Get the Slider named 'controllerOpacitySlider'
    controllerOpacitySlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"controllerOpacitySlider"));
    // Get the TextBox named 'leftKeyBox'
    leftKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"leftKeyBox"));
    // Get the TextBox named 'upKeyBox'
    upKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"upKeyBox"));
    // Get the TextBox named 'rightKeyBox'
    rightKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"rightKeyBox"));
    // Get the TextBox named 'downKeyBox'
    downKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"downKeyBox"));
    // Get the TextBox named 'aKeyBox'
    aKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"aKeyBox"));
    // Get the TextBox named 'bKeyBox'
    bKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"bKeyBox"));
    // Get the TextBox named 'xKeyBox'
    xKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"xKeyBox"));
    // Get the TextBox named 'yKeyBox'
    yKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"yKeyBox"));
    // Get the TextBox named 'lKeyBox'
    lKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"lKeyBox"));
    // Get the TextBox named 'rKeyBox'
    rKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"rKeyBox"));
    // Get the TextBox named 'startKeyBox'
    startKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"startKeyBox"));
    // Get the TextBox named 'selectKeyBox'
    selectKeyBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"selectKeyBox"));
    // Get the TextBox named 'turboModeBox'
    turboModeBox = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"turboModeBox"));
    // Get the TextBlock named 'opacityValueLabel'
    opacityValueLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"opacityValueLabel"));
    // Get the TextBlock named 'valueLabel'
    valueLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"valueLabel"));
    // Get the TextBlock named 'deadzoneLabel2'
    deadzoneLabel2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"deadzoneLabel2"));
    // Get the TextBlock named 'deadzoneLabel'
    deadzoneLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"deadzoneLabel"));
}

void ::Win8Snes9x::InputSettingsPane::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&InputSettingsPane::BackClick);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&InputSettingsPane::assignControlToggle_Toggled_1);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&InputSettingsPane::touchToggle_Toggled);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&InputSettingsPane::buttonStyleToggle_Toggled_1);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&InputSettingsPane::touchControlPosToggle_Toggled);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&InputSettingsPane::touchButtonStyleToggle_Toggled_1);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Selector^>(target))->SelectionChanged +=
            ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&InputSettingsPane::dpadComboBox_SelectionChanged_1);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::RangeBase^>(target))->ValueChanged +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&InputSettingsPane::deadzoneSlider_ValueChanged_1);
        break;
    case 9:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::RangeBase^>(target))->ValueChanged +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&InputSettingsPane::controllerScaleSlider_ValueChanged_1);
        break;
    case 10:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::RangeBase^>(target))->ValueChanged +=
            ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&InputSettingsPane::controllerOpacitySlider_ValueChanged_1);
        break;
    case 11:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::leftKeyBox_KeyUp);
        break;
    case 12:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::upKeyBox_KeyUp);
        break;
    case 13:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::rightKeyBox_KeyUp);
        break;
    case 14:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::downKeyBox_KeyUp);
        break;
    case 15:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::aKeyBox_KeyUp);
        break;
    case 16:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::bKeyBox_KeyUp);
        break;
    case 17:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::xKeyBox_KeyUp);
        break;
    case 18:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::yKeyBox_KeyUp);
        break;
    case 19:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::lKeyBox_KeyUp);
        break;
    case 20:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::rKeyBox_KeyUp);
        break;
    case 21:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::startKeyBox_KeyUp);
        break;
    case 22:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::selectKeyBox_KeyUp);
        break;
    case 23:
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyDown +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::keyDown);
        (safe_cast<::Windows::UI::Xaml::UIElement^>(target))->KeyUp +=
            ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::Win8Snes9x::InputSettingsPane::*)(Platform::Object^, Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&InputSettingsPane::turboModeBox_KeyUp_1);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

