

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ToggleSwitch;
                ref class TextBlock;
                ref class ComboBox;
                ref class Slider;
                ref class TextBox;
            }
        }
    }
}

namespace Win8Snes9x
{
    partial ref class InputSettingsPane : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ assignControlToggle;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ touchToggle;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ buttonStyleToggle;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ touchControlPosToggle;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ touchButtonStyleToggle;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ dpadStyleLabel;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ dpadComboBox;
        private: ::Windows::UI::Xaml::Controls::Slider^ deadzoneSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ controllerScaleSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ controllerOpacitySlider;
        private: ::Windows::UI::Xaml::Controls::TextBox^ leftKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ upKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ rightKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ downKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ aKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ bKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ xKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ yKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ lKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ rKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ startKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ selectKeyBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ turboModeBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ opacityValueLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ valueLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ deadzoneLabel2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ deadzoneLabel;
    };
}

