

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ComboBox;
                ref class ToggleSwitch;
            }
        }
    }
}

namespace Win8Snes9x
{
    partial ref class VideoSettingsPane : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::ComboBox^ monitorComboBox;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ fpsToggle;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ skipComboBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ powerSkipComboBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ turboSkipComboBox;
    };
}

